[project]
name = "mcp-kubernetes"
version = "0.1.0"
description = "MCP Server for a Kubernetes cluster written in Python."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kubernetes>=32.0.1",
    "mcp[cli]>=1.8.1",
]
